# Generated by Django 4.1.3 on 2022-12-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_numero_post_requisitos1_post_requisitos2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
