# Generated by Django 4.1.3 on 2022-12-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_ubicacion_vip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='titulo',
            new_name='titulos',
        ),
    ]
